import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
import UserEntity from "./user.entity.js";

/**
 * Persists summarized diary-chat conversations (journals) for the MyLog feature.
 *
 * Each record is created when a user ends a diary chat session. The AI generates
 * a summary of the conversation including an emotional arc assessment.
 */
@Entity({ name: "my_log_journals" })
class MyLogJournalEntity {
  @PrimaryGeneratedColumn("increment")
  id!: number;

  /**
   * Vietnamese summary of the diary chat session generated by AI.
   */
  @Column({ type: "text" })
  summary!: string;

  /**
   * English emotional arc summary of the session generated by AI.
   */
  @Column({ name: "emotional_summary", type: "text", nullable: true })
  emotionalSummary?: string | null;

  @Column({ name: "user_id", type: "int" })
  userId!: number;

  @ManyToOne(() => UserEntity, { nullable: false, onDelete: "CASCADE" })
  @JoinColumn({ name: "user_id" })
  user!: UserEntity;

  @CreateDateColumn({ name: "created_at", type: "datetime" })
  createdAt!: Date;
}

export default MyLogJournalEntity;
