import fs from "fs/promises";
import path from "path";

const CLIENT_DIST_DIR = path.resolve(process.cwd(), "..", "client", "dist");
const OUTPUT_PATH = path.resolve(process.cwd(), "src", "embedded-client.ts");

const textExtensions = new Set([
  ".html",
  ".js",
  ".css",
  ".json",
  ".svg",
  ".txt",
  ".map",
  ".xml"
]);

const contentTypes = new Map<string, string>([
  [".html", "text/html; charset=utf-8"],
  [".js", "text/javascript; charset=utf-8"],
  [".css", "text/css; charset=utf-8"],
  [".json", "application/json; charset=utf-8"],
  [".svg", "image/svg+xml; charset=utf-8"],
  [".txt", "text/plain; charset=utf-8"],
  [".map", "application/json; charset=utf-8"],
  [".xml", "application/xml; charset=utf-8"],
  [".ico", "image/x-icon"],
  [".png", "image/png"],
  [".jpg", "image/jpeg"],
  [".jpeg", "image/jpeg"],
  [".gif", "image/gif"],
  [".webp", "image/webp"],
  [".woff", "font/woff"],
  [".woff2", "font/woff2"],
  [".ttf", "font/ttf"],
  [".otf", "font/otf"],
  [".eot", "application/vnd.ms-fontobject"],
  [".mp3", "audio/mpeg"],
  [".wav", "audio/wav"],
  [".mp4", "video/mp4"],
  [".webm", "video/webm"]
]);

/**
 * Recursively gathers file paths within a directory.
 *
 * @param dir - Root directory to walk.
 * @returns Array of absolute file paths.
 */
const walkDir = async (dir: string): Promise<string[]> => {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkDir(entryPath)));
    } else {
      files.push(entryPath);
    }
  }

  return files;
};

/**
 * Resolves the content type for a file extension.
 *
 * @param extension - File extension including the leading dot.
 * @returns MIME type string.
 */
const getContentType = (extension: string) => contentTypes.get(extension) ?? "application/octet-stream";

/**
 * Generates the embedded client module for bundling.
 */
const generateEmbeddedClient = async () => {
  try {
    await fs.access(CLIENT_DIST_DIR);
  } catch {
    throw new Error(`Client build not found at ${CLIENT_DIST_DIR}. Run npm run build --workspace client first.`);
  }

  const files = await walkDir(CLIENT_DIST_DIR);
  const entries: string[] = [];

  for (const filePath of files) {
    const relativePath = path.relative(CLIENT_DIST_DIR, filePath).split(path.sep).join("/");
    const extension = path.extname(filePath).toLowerCase();
    const contentType = getContentType(extension);
    const isText = textExtensions.has(extension);
    const data = await fs.readFile(filePath);
    const content = isText ? data.toString("utf8") : data.toString("base64");
    const encoding = isText ? "utf8" : "base64";

    entries.push(
      `  ${JSON.stringify(relativePath)}: { content: ${JSON.stringify(content)}, contentType: ${JSON.stringify(
        contentType
      )}, encoding: ${JSON.stringify(encoding)} }`
    );
  }

  const output = `// This file is auto-generated by src/scripts/generate-embedded-client.ts.
// Do not edit manually.

export type EmbeddedClientAsset = {
  content: string;
  contentType: string;
  encoding: "utf8" | "base64";
};

export const embeddedClientAssets: Record<string, EmbeddedClientAsset> = {
${entries.join(",\n")}
};

export const embeddedClientIndexHtml = embeddedClientAssets["index.html"]?.content ?? "";
`;

  await fs.writeFile(OUTPUT_PATH, output, "utf8");
  console.log(`Embedded client assets generated at ${OUTPUT_PATH}.`);
};

void generateEmbeddedClient();
